"""Add cascade deletes to all foreign keys

Revision ID: 2cb38a1bdf7d
Revises: 5ca5c0a6dbb9
Create Date: 2026-06-26 13:30:24.607047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb38a1bdf7d'
down_revision: Union[str, Sequence[str], None] = '5ca5c0a6dbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_user_id_fkey'), 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('journal_entries_user_id_fkey'), 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('line_items_journal_entry_id_fkey'), 'line_items', type_='foreignkey')
    op.drop_constraint(op.f('line_items_account_id_fkey'), 'line_items', type_='foreignkey')
    op.create_foreign_key(None, 'line_items', 'journal_entries', ['journal_entry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'line_items', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'line_items', type_='foreignkey')
    op.drop_constraint(None, 'line_items', type_='foreignkey')
    op.create_foreign_key(op.f('line_items_account_id_fkey'), 'line_items', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('line_items_journal_entry_id_fkey'), 'line_items', 'journal_entries', ['journal_entry_id'], ['id'])
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key(op.f('journal_entries_user_id_fkey'), 'journal_entries', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key(op.f('accounts_user_id_fkey'), 'accounts', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
