"""add merchant_cache table

Revision ID: 8b0c810eb7b5
Revises: 714c63005e42
Create Date: 2026-06-19 17:13:42.083227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0c810eb7b5'
down_revision: Union[str, Sequence[str], None] = '714c63005e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_key', sa.String(), nullable=True),
    sa.Column('clean_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('irs_line', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_cache_id'), 'merchant_cache', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_cache_merchant_key'), 'merchant_cache', ['merchant_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_cache_merchant_key'), table_name='merchant_cache')
    op.drop_index(op.f('ix_merchant_cache_id'), table_name='merchant_cache')
    op.drop_table('merchant_cache')
    # ### end Alembic commands ###
