"""Add tx_hash to transactions

Revision ID: bd50379ff3fe
Revises: 8b0c810eb7b5
Create Date: 2026-06-20 13:59:13.303389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd50379ff3fe'
down_revision: Union[str, Sequence[str], None] = '8b0c810eb7b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('tx_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_column('transactions', 'tx_hash')
    # ### end Alembic commands ###
